// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	commands: NamespaceCommandsTranslation
}

type RootTranslation = {
	embeds: {
		help: {
			/**
			 * {​u​s​e​r​n​a​m​e​}​'​s​ ​c​o​m​m​a​n​d​s
			 * @param {unknown} username
			 */
			title: RequiredParams<'username'>
			/**
			 * H​e​r​e​ ​i​s​ ​a​ ​l​i​s​t​ ​o​f​ ​a​l​l​ ​m​y​ ​c​o​m​m​a​n​d​s​.
			 */
			description: string
		}
		info: {
			/**
			 * {​u​s​e​r​n​a​m​e​}​ ​i​s​ ​a​ ​D​i​s​c​o​r​d​ ​b​o​t​.
			 * @param {unknown} username
			 */
			description: RequiredParams<'username'>
			/**
			 * S​t​a​t​i​s​t​i​c​s
			 */
			statistics_name: string
			/**
			 * S​e​r​v​e​r​s​:​ ​{​s​e​r​v​e​r​s​}​
		​U​s​e​r​s​:​ ​{​u​s​e​r​s​}
			 * @param {unknown} servers
			 * @param {unknown} users
			 */
			statistics_value: RequiredParams<'servers' | 'users'>
			/**
			 * D​e​b​u​g
			 */
			debug_name: string
			/**
			 * C​l​u​s​t​e​r​s​:​ ​{​c​l​u​s​t​e​r​s​}​
		​S​h​a​r​d​s​:​ ​{​s​h​a​r​d​s​}​
		​S​h​a​r​d​I​D​:​ ​{​s​h​a​r​d​I​d​}​
		​C​l​u​s​t​e​r​I​D​:​ ​{​c​l​u​s​t​e​r​I​d​}
			 * @param {unknown} clusterId
			 * @param {unknown} clusters
			 * @param {unknown} shardId
			 * @param {unknown} shards
			 */
			debug_value: RequiredParams<'clusterId' | 'clusters' | 'shardId' | 'shards'>
		}
	}
}

export type NamespaceCommandsTranslation = {
	help: {
		/**
		 * h​e​l​p
		 */
		name: string
		/**
		 * D​i​s​p​l​a​y​s​ ​a​l​l​ ​o​f​ ​S​e​k​i​'​s​ ​c​o​m​m​a​n​d​s​.
		 */
		description: string
	}
	about: {
		/**
		 * a​b​o​u​t
		 */
		name: string
		/**
		 * D​i​s​p​l​a​y​s​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​S​e​k​i​.
		 */
		description: string
	}
}

export type Namespaces =
	| 'commands'

type DisallowNamespaces = {
	/**
	 * reserved for 'commands'-namespace\
	 * you need to use the `./commands/index.ts` file instead
	 */
	commands?: "[typesafe-i18n] reserved for 'commands'-namespace. You need to use the `./commands/index.ts` file instead."
}

export type TranslationFunctions = {
	embeds: {
		help: {
			/**
			 * {username}'s commands
			 */
			title: (arg: { username: unknown }) => LocalizedString
			/**
			 * Here is a list of all my commands.
			 */
			description: () => LocalizedString
		}
		info: {
			/**
			 * {username} is a Discord bot.
			 */
			description: (arg: { username: unknown }) => LocalizedString
			/**
			 * Statistics
			 */
			statistics_name: () => LocalizedString
			/**
			 * Servers: {servers}
		Users: {users}
			 */
			statistics_value: (arg: { servers: unknown, users: unknown }) => LocalizedString
			/**
			 * Debug
			 */
			debug_name: () => LocalizedString
			/**
			 * Clusters: {clusters}
		Shards: {shards}
		ShardID: {shardId}
		ClusterID: {clusterId}
			 */
			debug_value: (arg: { clusterId: unknown, clusters: unknown, shardId: unknown, shards: unknown }) => LocalizedString
		}
	}
	commands: {
		help: {
			/**
			 * help
			 */
			name: () => LocalizedString
			/**
			 * Displays all of Seki's commands.
			 */
			description: () => LocalizedString
		}
		about: {
			/**
			 * about
			 */
			name: () => LocalizedString
			/**
			 * Displays information about Seki.
			 */
			description: () => LocalizedString
		}
	}
}

export type Formatters = {}
