// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'nl'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	commands: NamespaceCommandsTranslation
}

type RootTranslation = {
	embeds: {
		help: {
			/**
			 * {​u​s​e​r​n​a​m​e​}​'​s​ ​c​o​m​m​a​n​d​s
			 * @param {unknown} username
			 */
			title: RequiredParams<'username'>
			/**
			 * H​e​r​e​ ​i​s​ ​a​ ​l​i​s​t​ ​o​f​ ​a​l​l​ ​m​y​ ​c​o​m​m​a​n​d​s​.
			 */
			description: string
		}
		info: {
			/**
			 * {​u​s​e​r​n​a​m​e​}​ ​i​s​ ​a​n​ ​i​n​t​u​i​t​i​v​e​ ​a​n​d​ ​u​s​e​r​-​f​r​i​e​n​d​l​y​ ​D​i​s​c​o​r​d​ ​b​o​t​ ​c​o​n​n​e​c​t​e​d​ ​t​o​ ​h​t​t​p​s​:​/​/​p​a​l​i​a​p​e​d​i​a​.​c​o​m​ ​a​n​d​ ​h​a​s​ ​b​e​e​n​ ​c​r​e​a​t​e​d​ ​b​y​ ​[​g​l​a​z​k​0​]​(​d​i​s​c​o​r​d​:​/​/​-​/​u​s​e​r​s​/​2​4​7​3​4​4​1​3​0​7​9​8​2​5​6​1​3​0​)​.
			 * @param {unknown} username
			 */
			description: RequiredParams<'username'>
			/**
			 * S​t​a​t​i​s​t​i​c​s
			 */
			statistics_name: string
			/**
			 * S​e​r​v​e​r​s​:​ ​{​s​e​r​v​e​r​s​}​
		​U​s​e​r​s​:​ ​{​u​s​e​r​s​}
			 * @param {unknown} servers
			 * @param {unknown} users
			 */
			statistics_value: RequiredParams<'servers' | 'users'>
			/**
			 * D​e​b​u​g
			 */
			debug_name: string
			/**
			 * C​l​u​s​t​e​r​s​:​ ​{​c​l​u​s​t​e​r​s​}​
		​S​h​a​r​d​s​:​ ​{​s​h​a​r​d​s​}​
		​S​h​a​r​d​I​D​:​ ​{​s​h​a​r​d​I​d​}​
		​C​l​u​s​t​e​r​I​D​:​ ​{​c​l​u​s​t​e​r​I​d​}
			 * @param {unknown} clusterId
			 * @param {unknown} clusters
			 * @param {unknown} shardId
			 * @param {unknown} shards
			 */
			debug_value: RequiredParams<'clusterId' | 'clusters' | 'shardId' | 'shards'>
		}
	}
	interactions: {
		settings: {
			news: {
				/**
				 * N​e​w​s​ ​w​i​l​l​ ​n​o​w​ ​b​e​ ​s​e​n​t​ ​i​n​ ​{​c​h​a​n​n​e​l​}​.
				 * @param {unknown} channel
				 */
				enabled: RequiredParams<'channel'>
				/**
				 * N​e​w​s​ ​a​r​e​ ​n​o​t​ ​e​n​a​b​l​e​d​ ​f​o​r​ ​t​h​i​s​ ​s​e​r​v​e​r​.
				 */
				not_enabled: string
				/**
				 * N​e​w​s​ ​w​i​l​l​ ​n​o​ ​l​o​n​g​e​r​ ​b​e​ ​s​e​n​t​ ​i​n​ ​{​c​h​a​n​n​e​l​}​.
				 * @param {unknown} channel
				 */
				disabled: RequiredParams<'channel'>
			}
			weekly_wants: {
				/**
				 * W​e​e​k​l​y​ ​w​a​n​t​s​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​w​i​l​l​ ​n​o​w​ ​b​e​ ​s​e​n​t​ ​i​n​ ​{​c​h​a​n​n​e​l​}​.
				 * @param {unknown} channel
				 */
				enabled: RequiredParams<'channel'>
				/**
				 * W​e​e​k​l​y​ ​w​a​n​t​s​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​a​r​e​ ​n​o​t​ ​e​n​a​b​l​e​d​ ​f​o​r​ ​t​h​i​s​ ​s​e​r​v​e​r​.
				 */
				not_enabled: string
				/**
				 * W​e​e​k​l​y​ ​w​a​n​t​s​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​w​i​l​l​ ​n​o​ ​l​o​n​g​e​r​ ​b​e​ ​s​e​n​t​ ​i​n​ ​{​c​h​a​n​n​e​l​}​.
				 * @param {unknown} channel
				 */
				disabled: RequiredParams<'channel'>
			}
			locale: {
				/**
				 * T​h​e​ ​l​o​c​a​l​e​ ​h​a​s​ ​b​e​e​n​ ​s​e​t​ ​t​o​ ​{​l​o​c​a​l​e​}​.
				 * @param {unknown} locale
				 */
				success: RequiredParams<'locale'>
			}
		}
		miscellaneous: {
			/**
			 * I​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​v​i​e​w​ ​o​r​ ​s​e​n​d​ ​m​e​s​s​a​g​e​s​ ​i​n​ ​{​c​h​a​n​n​e​l​}​.
			 * @param {unknown} channel
			 */
			no_permissions: RequiredParams<'channel'>
			/**
			 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d​.
			 */
			no_results: string
			/**
			 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d​ ​f​o​r​ ​"​{​q​u​e​r​y​}​"​.
			 * @param {unknown} query
			 */
			no_results_for: RequiredParams<'query'>
		}
	}
}

export type NamespaceCommandsTranslation = {
	settings: {
		/**
		 * s​e​t​t​i​n​g​s
		 */
		name: string
		/**
		 * M​a​n​a​g​e​ ​y​o​u​r​ ​s​e​r​v​e​r​ ​s​e​t​t​i​n​g​s​.
		 */
		description: string
	}
	'settings.locale': {
		/**
		 * l​o​c​a​l​e
		 */
		name: string
		/**
		 * C​h​a​n​g​e​ ​t​h​e​ ​l​o​c​a​l​e​ ​o​f​ ​Z​e​k​i​ ​f​o​r​ ​y​o​u​r​ ​s​e​r​v​e​r​.
		 */
		description: string
	}
	'settings.locale.value': {
		/**
		 * v​a​l​u​e
		 */
		name: string
		/**
		 * W​h​i​c​h​ ​l​o​c​a​l​e​ ​d​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​s​e​t​ ​f​o​r​ ​y​o​u​r​ ​s​e​r​v​e​r​?
		 */
		description: string
	}
	'settings.news': {
		/**
		 * n​e​w​s
		 */
		name: string
		/**
		 * M​a​n​a​g​e​ ​t​h​e​ ​n​e​w​s​ ​s​e​t​t​i​n​g​s​ ​o​f​ ​y​o​u​r​ ​s​e​r​v​e​r​.
		 */
		description: string
	}
	'settings.news.enable': {
		/**
		 * e​n​a​b​l​e
		 */
		name: string
		/**
		 * E​n​a​b​l​e​ ​t​h​e​ ​n​e​w​s​ ​f​e​a​t​u​r​e​ ​f​o​r​ ​y​o​u​r​ ​s​e​r​v​e​r​.
		 */
		description: string
	}
	'settings.news.enable.channel': {
		/**
		 * c​h​a​n​n​e​l
		 */
		name: string
		/**
		 * T​h​e​ ​c​h​a​n​n​e​l​ ​w​h​e​r​e​ ​n​e​w​s​ ​w​i​l​l​ ​b​e​ ​s​e​n​t​.
		 */
		description: string
	}
	'settings.news.disable': {
		/**
		 * d​i​s​a​b​l​e
		 */
		name: string
		/**
		 * D​i​s​a​b​l​e​ ​t​h​e​ ​n​e​w​s​ ​f​e​a​t​u​r​e​ ​f​o​r​ ​y​o​u​r​ ​s​e​r​v​e​r​.
		 */
		description: string
	}
	'settings.weekly-wants': {
		/**
		 * w​e​e​k​l​y​-​w​a​n​t​s
		 */
		name: string
		/**
		 * M​a​n​a​g​e​ ​t​h​e​ ​w​e​e​k​l​y​ ​w​a​n​t​s​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​o​f​ ​y​o​u​r​ ​s​e​r​v​e​r​.
		 */
		description: string
	}
	'settings.weekly-wants.enable': {
		/**
		 * e​n​a​b​l​e
		 */
		name: string
		/**
		 * E​n​a​b​l​e​ ​t​h​e​ ​w​e​e​k​l​y​ ​w​a​n​t​s​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​f​o​r​ ​y​o​u​r​ ​s​e​r​v​e​r​.
		 */
		description: string
	}
	'settings.weekly-wants.enable.channel': {
		/**
		 * c​h​a​n​n​e​l
		 */
		name: string
		/**
		 * T​h​e​ ​c​h​a​n​n​e​l​ ​w​h​e​r​e​ ​w​e​e​k​l​y​ ​w​a​n​t​s​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​w​i​l​l​ ​b​e​ ​s​e​n​t​.
		 */
		description: string
	}
	'settings.weekly-wants.enable.daily': {
		/**
		 * d​a​i​l​y
		 */
		name: string
		/**
		 * W​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​r​e​c​e​i​v​e​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​f​o​r​ ​d​a​i​l​y​ ​r​e​f​r​e​s​h​e​s​?​ ​(​T​r​u​e​ ​f​o​r​ ​y​e​s​,​ ​F​a​l​s​e​ ​f​o​r​ ​n​o​)
		 */
		description: string
	}
	'settings.weekly-wants.enable.weekly': {
		/**
		 * w​e​e​k​l​y
		 */
		name: string
		/**
		 * W​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​r​e​c​e​i​v​e​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​f​o​r​ ​w​e​e​k​l​y​ ​r​e​f​r​e​s​h​e​s​?​ ​(​T​r​u​e​ ​f​o​r​ ​y​e​s​,​ ​F​a​l​s​e​ ​f​o​r​ ​n​o​)
		 */
		description: string
	}
	'settings.weekly-wants.disable': {
		/**
		 * d​i​s​a​b​l​e
		 */
		name: string
		/**
		 * D​i​s​a​b​l​e​ ​t​h​e​ ​w​e​e​k​l​y​ ​w​a​n​t​s​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​f​o​r​ ​y​o​u​r​ ​s​e​r​v​e​r​.
		 */
		description: string
	}
	help: {
		/**
		 * h​e​l​p
		 */
		name: string
		/**
		 * D​i​s​p​l​a​y​s​ ​a​l​l​ ​o​f​ ​Z​e​k​i​'​s​ ​c​o​m​m​a​n​d​s​.
		 */
		description: string
	}
	about: {
		/**
		 * a​b​o​u​t
		 */
		name: string
		/**
		 * D​i​s​p​l​a​y​s​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​Z​e​k​i​.
		 */
		description: string
	}
	search: {
		/**
		 * s​e​a​r​c​h
		 */
		name: string
		/**
		 * S​e​a​r​c​h​e​s​ ​f​o​r​ ​a​n​y​ ​t​y​p​e​ ​o​f​ ​d​a​t​a​.
		 */
		description: string
	}
	'search.query': {
		/**
		 * q​u​e​r​y
		 */
		name: string
		/**
		 * T​h​e​ ​q​u​e​r​y​ ​t​o​ ​s​e​a​r​c​h​ ​f​o​r​.
		 */
		description: string
	}
	quest: {
		/**
		 * q​u​e​s​t
		 */
		name: string
		/**
		 * S​e​a​r​c​h​e​s​ ​f​o​r​ ​a​ ​q​u​e​s​t​.
		 */
		description: string
	}
	'quest.query': {
		/**
		 * q​u​e​r​y
		 */
		name: string
		/**
		 * T​h​e​ ​q​u​e​r​y​ ​t​o​ ​s​e​a​r​c​h​ ​f​o​r​.
		 */
		description: string
	}
	villager: {
		/**
		 * v​i​l​l​a​g​e​r
		 */
		name: string
		/**
		 * S​e​a​r​c​h​e​s​ ​f​o​r​ ​a​ ​v​i​l​l​a​g​e​r​.
		 */
		description: string
	}
	'villager.query': {
		/**
		 * q​u​e​r​y
		 */
		name: string
		/**
		 * T​h​e​ ​q​u​e​r​y​ ​t​o​ ​s​e​a​r​c​h​ ​f​o​r​.
		 */
		description: string
	}
	recipe: {
		/**
		 * r​e​c​i​p​e
		 */
		name: string
		/**
		 * S​e​a​r​c​h​e​s​ ​f​o​r​ ​a​ ​r​e​c​i​p​e​.
		 */
		description: string
	}
	'recipe.query': {
		/**
		 * q​u​e​r​y
		 */
		name: string
		/**
		 * T​h​e​ ​q​u​e​r​y​ ​t​o​ ​s​e​a​r​c​h​ ​f​o​r​.
		 */
		description: string
	}
	'recipe.amount': {
		/**
		 * a​m​o​u​n​t
		 */
		name: string
		/**
		 * T​h​e​ ​a​m​o​u​n​t​ ​o​f​ ​i​t​e​m​s​ ​t​o​ ​c​r​a​f​t​.
		 */
		description: string
	}
	item: {
		/**
		 * i​t​e​m
		 */
		name: string
		/**
		 * S​e​a​r​c​h​e​s​ ​f​o​r​ ​a​n​ ​i​t​e​m​.
		 */
		description: string
	}
	'item.query': {
		/**
		 * q​u​e​r​y
		 */
		name: string
		/**
		 * T​h​e​ ​q​u​e​r​y​ ​t​o​ ​s​e​a​r​c​h​ ​f​o​r​.
		 */
		description: string
	}
}

export type Namespaces =
	| 'commands'

type DisallowNamespaces = {
	/**
	 * reserved for 'commands'-namespace\
	 * you need to use the `./commands/index.ts` file instead
	 */
	commands?: "[typesafe-i18n] reserved for 'commands'-namespace. You need to use the `./commands/index.ts` file instead."
}

export type TranslationFunctions = {
	embeds: {
		help: {
			/**
			 * {username}'s commands
			 */
			title: (arg: { username: unknown }) => LocalizedString
			/**
			 * Here is a list of all my commands.
			 */
			description: () => LocalizedString
		}
		info: {
			/**
			 * {username} is an intuitive and user-friendly Discord bot connected to https://paliapedia.com and has been created by [glazk0](discord://-/users/247344130798256130).
			 */
			description: (arg: { username: unknown }) => LocalizedString
			/**
			 * Statistics
			 */
			statistics_name: () => LocalizedString
			/**
			 * Servers: {servers}
		Users: {users}
			 */
			statistics_value: (arg: { servers: unknown, users: unknown }) => LocalizedString
			/**
			 * Debug
			 */
			debug_name: () => LocalizedString
			/**
			 * Clusters: {clusters}
		Shards: {shards}
		ShardID: {shardId}
		ClusterID: {clusterId}
			 */
			debug_value: (arg: { clusterId: unknown, clusters: unknown, shardId: unknown, shards: unknown }) => LocalizedString
		}
	}
	interactions: {
		settings: {
			news: {
				/**
				 * News will now be sent in {channel}.
				 */
				enabled: (arg: { channel: unknown }) => LocalizedString
				/**
				 * News are not enabled for this server.
				 */
				not_enabled: () => LocalizedString
				/**
				 * News will no longer be sent in {channel}.
				 */
				disabled: (arg: { channel: unknown }) => LocalizedString
			}
			weekly_wants: {
				/**
				 * Weekly wants notifications will now be sent in {channel}.
				 */
				enabled: (arg: { channel: unknown }) => LocalizedString
				/**
				 * Weekly wants notifications are not enabled for this server.
				 */
				not_enabled: () => LocalizedString
				/**
				 * Weekly wants notifications will no longer be sent in {channel}.
				 */
				disabled: (arg: { channel: unknown }) => LocalizedString
			}
			locale: {
				/**
				 * The locale has been set to {locale}.
				 */
				success: (arg: { locale: unknown }) => LocalizedString
			}
		}
		miscellaneous: {
			/**
			 * I don't have the permission to view or send messages in {channel}.
			 */
			no_permissions: (arg: { channel: unknown }) => LocalizedString
			/**
			 * No results found.
			 */
			no_results: () => LocalizedString
			/**
			 * No results found for "{query}".
			 */
			no_results_for: (arg: { query: unknown }) => LocalizedString
		}
	}
	commands: {
		settings: {
			/**
			 * settings
			 */
			name: () => LocalizedString
			/**
			 * Manage your server settings.
			 */
			description: () => LocalizedString
		}
		'settings.locale': {
			/**
			 * locale
			 */
			name: () => LocalizedString
			/**
			 * Change the locale of Zeki for your server.
			 */
			description: () => LocalizedString
		}
		'settings.locale.value': {
			/**
			 * value
			 */
			name: () => LocalizedString
			/**
			 * Which locale do you want to set for your server?
			 */
			description: () => LocalizedString
		}
		'settings.news': {
			/**
			 * news
			 */
			name: () => LocalizedString
			/**
			 * Manage the news settings of your server.
			 */
			description: () => LocalizedString
		}
		'settings.news.enable': {
			/**
			 * enable
			 */
			name: () => LocalizedString
			/**
			 * Enable the news feature for your server.
			 */
			description: () => LocalizedString
		}
		'settings.news.enable.channel': {
			/**
			 * channel
			 */
			name: () => LocalizedString
			/**
			 * The channel where news will be sent.
			 */
			description: () => LocalizedString
		}
		'settings.news.disable': {
			/**
			 * disable
			 */
			name: () => LocalizedString
			/**
			 * Disable the news feature for your server.
			 */
			description: () => LocalizedString
		}
		'settings.weekly-wants': {
			/**
			 * weekly-wants
			 */
			name: () => LocalizedString
			/**
			 * Manage the weekly wants notifications of your server.
			 */
			description: () => LocalizedString
		}
		'settings.weekly-wants.enable': {
			/**
			 * enable
			 */
			name: () => LocalizedString
			/**
			 * Enable the weekly wants notifications for your server.
			 */
			description: () => LocalizedString
		}
		'settings.weekly-wants.enable.channel': {
			/**
			 * channel
			 */
			name: () => LocalizedString
			/**
			 * The channel where weekly wants notifications will be sent.
			 */
			description: () => LocalizedString
		}
		'settings.weekly-wants.enable.daily': {
			/**
			 * daily
			 */
			name: () => LocalizedString
			/**
			 * Would you like to receive notifications for daily refreshes? (True for yes, False for no)
			 */
			description: () => LocalizedString
		}
		'settings.weekly-wants.enable.weekly': {
			/**
			 * weekly
			 */
			name: () => LocalizedString
			/**
			 * Would you like to receive notifications for weekly refreshes? (True for yes, False for no)
			 */
			description: () => LocalizedString
		}
		'settings.weekly-wants.disable': {
			/**
			 * disable
			 */
			name: () => LocalizedString
			/**
			 * Disable the weekly wants notifications for your server.
			 */
			description: () => LocalizedString
		}
		help: {
			/**
			 * help
			 */
			name: () => LocalizedString
			/**
			 * Displays all of Zeki's commands.
			 */
			description: () => LocalizedString
		}
		about: {
			/**
			 * about
			 */
			name: () => LocalizedString
			/**
			 * Displays information about Zeki.
			 */
			description: () => LocalizedString
		}
		search: {
			/**
			 * search
			 */
			name: () => LocalizedString
			/**
			 * Searches for any type of data.
			 */
			description: () => LocalizedString
		}
		'search.query': {
			/**
			 * query
			 */
			name: () => LocalizedString
			/**
			 * The query to search for.
			 */
			description: () => LocalizedString
		}
		quest: {
			/**
			 * quest
			 */
			name: () => LocalizedString
			/**
			 * Searches for a quest.
			 */
			description: () => LocalizedString
		}
		'quest.query': {
			/**
			 * query
			 */
			name: () => LocalizedString
			/**
			 * The query to search for.
			 */
			description: () => LocalizedString
		}
		villager: {
			/**
			 * villager
			 */
			name: () => LocalizedString
			/**
			 * Searches for a villager.
			 */
			description: () => LocalizedString
		}
		'villager.query': {
			/**
			 * query
			 */
			name: () => LocalizedString
			/**
			 * The query to search for.
			 */
			description: () => LocalizedString
		}
		recipe: {
			/**
			 * recipe
			 */
			name: () => LocalizedString
			/**
			 * Searches for a recipe.
			 */
			description: () => LocalizedString
		}
		'recipe.query': {
			/**
			 * query
			 */
			name: () => LocalizedString
			/**
			 * The query to search for.
			 */
			description: () => LocalizedString
		}
		'recipe.amount': {
			/**
			 * amount
			 */
			name: () => LocalizedString
			/**
			 * The amount of items to craft.
			 */
			description: () => LocalizedString
		}
		item: {
			/**
			 * item
			 */
			name: () => LocalizedString
			/**
			 * Searches for an item.
			 */
			description: () => LocalizedString
		}
		'item.query': {
			/**
			 * query
			 */
			name: () => LocalizedString
			/**
			 * The query to search for.
			 */
			description: () => LocalizedString
		}
	}
}

export type Formatters = {}
